---
apiVersion: v1
kind: Secret
metadata:
    name: '{{ .Values.SERVICE_NAME }}-secret'
    namespace: '{{ .Values.NAMESPACE }}'
    labels:
      app.kubernetes.io/part-of: 'Cloud-Core'
      app.kubernetes.io/managed-by: 'saasDeployer'
      deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
    annotations:
        kubernetes.io/service-account.name: '{{ .Values.SERVICE_NAME }}'
type: kubernetes.io/service-account-token

