# ============== DEPLOYMENT VARIABLES ============================
MONITORING_ENABLED: true
CLOUD_TOPOLOGY_KEY: kubernetes.io/hostname
READONLY_CONTAINER_FILE_SYSTEM_ENABLED: false
IMAGE_REPOSITORY: 'ghcr.io/netcracker/qubership-core-paas-mediation'

paasMediation:
  readinessProbe:
    initialDelaySeconds: 5
    timeoutSeconds: 30
  livenessProbe:
    initialDelaySeconds: 180
    timeoutSeconds: 30

# ============== SERVICE VARIABLES ============================
LOG_LEVEL: "info"
SERVICE_NAME: 'paas-mediation'

TRACING_ENABLED: false
TRACING_HOST: 'nc-diagnostic-agent'
TRACING_SAMPLER_RATELIMITING: 10

DISABLE_DEPRECATED_API: false
CONSUL_ENABLED: false
CONSUL_URL: ''

K8S_SERVICE_TYPE: 'HEADLESS'
